#!/bin/bash
        
SCRIPT_PATH=$(dirname $(realpath $0))
# The file is the only .tex file in the directory
ORIGINAL_FILE=$(ls $SCRIPT_PATH | grep .tex)

# Add a '_fr' suffix before the extension
FRENCH_FILE=$(echo $ORIGINAL_FILE | sed 's/\(.*\)\(\..*\)/\1_fr\2/')
# Add a '_en' suffix before the extension
ENGLISH_FILE=$(echo $ORIGINAL_FILE | sed 's/\(.*\)\(\..*\)/\1_en\2/')


#### We start by french

# First, we need to ensure that the line \usepackage[something]{tagging} is set to 'french'
sed -i 's/\\usepackage\(\[.*\]\){tagging}/\\usepackage[french]{tagging}/' $ORIGINAL_FILE

# Remove the .tex extension
FILE_WITHOUT_EXTENSION=$(echo $FRENCH_FILE | sed 's/\(.*\)\..*/\1/')

# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE
# Call biber
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex biber $FILE_WITHOUT_EXTENSION
# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE
# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE

#### We continue with english

# First, we need to ensure that the line \usepackage[something]{tagging} is set to 'english'
sed -i 's/\\usepackage\(\[.*\]\){tagging}/\\usepackage[english]{tagging}/' $ORIGINAL_FILE

# Remove the .tex extension
FILE_WITHOUT_EXTENSION=$(echo $ENGLISH_FILE | sed 's/\(.*\)\..*/\1/')

# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE
# Call biber
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex biber $FILE_WITHOUT_EXTENSION
# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE
# Call pdflatex
docker run --rm -i -v $SCRIPT_PATH:/data sql-lualatex pdflatex -jobname="$FILE_WITHOUT_EXTENSION" $ORIGINAL_FILE

#### In the end, we delete the files generated by the compilation (except the .pdf files)

rm -f $SCRIPT_PATH/*.aux
rm -f $SCRIPT_PATH/*.bbl
rm -f $SCRIPT_PATH/*.bcf
rm -f $SCRIPT_PATH/*.blg
rm -f $SCRIPT_PATH/*.log
rm -f $SCRIPT_PATH/*.run.xml
rm -f $SCRIPT_PATH/*.toc
rm -f $SCRIPT_PATH/*.out